providers:
  docker:
    exposedByDefault: false
    network: proxy
  file:
    filename: /dynamic.yml

api:
  insecure: false # Set to true if you want to access the dashboard on :8080

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

  traefik:
    address: ":8080"

certificatesResolvers:
  main:
    acme:
      email: certs@ethercreative.co.uk
      storage: acme.json
      httpChallenge:
        entryPoint: web
#      dnsChallenge:
#        provider: digitalocean
#        delayBeforeCheck: 0

accessLog:
  filePath: "/logs/access.log"
  fields:
    defaultMode: keep
    names:
      defaultMode: keep
    headers:
      defaultMode: keep
